---
server:
  port: 8771
spring:
  profiles: peer1
  application:
    name: eureka-ha
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8772/eureka/,http://peer3:8773/eureka/

---
server:
  port: 8772
spring:
  profiles: peer2
  application:
    name: eureka-ha
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8771/eureka/,http://peer3:8773/eureka/

---
server:
  port: 8773
spring:
  profiles: peer3
  application:
    name: eureka-ha
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer1:8771/eureka/,http://peer2:8772/eureka/

