server:
  # 8881 8882
  port: 8881
spring:
  application:
    name: config-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
## 刷新时，关闭安全验证
management:
  security:
    enabled: false