server:
  port: 8988
spring:
  application:
    name: zipkin-ping
  zipkin:
    baseUrl: http://localhost:9411
#  sleuth:
#    sampler:
#      percentage: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/