server:
  port: 8988
spring:
  application:
    name: zipkin-ping
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/